# Generated by Django 4.1.5 on 2023-01-17 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='users',
            old_name='password1',
            new_name='password',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password2',
        ),
    ]
