# Generated by Django 4.1.5 on 2023-01-19 15:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('website', models.URLField()),
                ('phone_number', models.CharField(max_length=50)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('restaurant_image', models.ImageField(default='', upload_to='image/photos/%Y/%m/%d/')),
            ],
        ),
    ]
