# Generated by Django 4.1.5 on 2023-01-19 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_restaurant_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
