# Generated by Django 4.1.5 on 2023-01-20 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_restaurant_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='restaurant_image',
        ),
    ]
